"""
Django settings for admin_panel project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@bown7drn*$2lugv(+12$__idww-^-dlo-27x4gt6t+q16bkms'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://37.27.202.254',
    'https://demo.octopus.com.az',
    'https://octopus.com.az',
]

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'admin_panel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'admin_panel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'api_db',
        'USER': 'api_user',
        'PASSWORD': 'pK4jbN/ob[g?4Slm',
        'HOST': '37.27.202.254' if DEBUG else '127.0.0.1', # Prod use localhost, Dev use external IP
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
APPEND_SLASH = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Jazzmin Settings
JAZZMIN_SETTINGS = {
    "site_title": "Octopus admin",
    "site_header": "Admin",
    "site_brand": "Admin Panel",


 
    "welcome_sign": "Welcome to the Admin Panel",
    "copyright": "Project Ltd",
    "search_model": ["core.User", "core.Company"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        "core.User": "fas fa-user",
        "core.Company": "fas fa-building",
        "core.Candidate": "fas fa-user-graduate",
        "core.Moderator": "fas fa-user-shield",
        "core.JobPost": "fas fa-briefcase",
        "core.JobApplication": "fas fa-file-alt",
        "core.Boost": "fas fa-rocket",
        "core.Industry": "fas fa-industry",
        "core.IndustryTranslation": "fas fa-language",        # translation üçün generic icon
        "core.Occupation": "fas fa-user-tie",
        "core.OccupationTranslation": "fas fa-language",
        "core.EmploymentType": "fas fa-clock",
        "core.EmploymentTypeTranslation": "fas fa-language",
        "core.EducationLevel": "fas fa-graduation-cap",
        "core.EducationLevelTranslation": "fas fa-language",
        "core.Level": "fas fa-layer-group",
        "core.LevelTranslation": "fas fa-language",
        "core.Skill": "fas fa-lightbulb",
        "core.CandidateSkill": "fas fa-lightbulb",
        "core.Language": "fas fa-language",
        "core.CandidateLanguageLevel": "fas fa-language",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
}
JAZZMIN_SETTINGS["show_ui_builder"] = False